update: improve missing trustpolicy error message (#282)
This PR improves the error message for a missing trustpolicy file [notaryproject/notation/#128](https://github.com/notaryproject/notation/issues/128#issuecomment-1448683454). This is the output when the trustpolicy is missing:
```
c889f3b9d811:notation kodysk$ ./bin/notation verify $IMAGE
Error: Trust policy is not present, please create trust policy at /Users/kodysk/Library/Application Support/notation/trustpolicy.json
```

Signed-off-by: Kody Kimberl kody.kimberl.work@gmail.com